language: c
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install libsdl2-dev
    - sudo apt-get install libsdl2-image-dev
script:
    - mkdir build && cd build && cmake .. && make utils_test && ctest -V
